### ISSUE TITLE
Trying to apply Dynamic NTK RoPE scaling into exllama.

### ISSUE THREAD

**Issue by Panchovix** [turboderp/exllama#126]
Hi there! Thanks for all the hard work.

As someone you have already seen, NTK RoPE scaling helps when applyng it on non-finetuned models.

Now, this has a cost when alpha is set higher to or higher at 4, as can you see in this graph.

![image](https://github.com/turboderp/exllama/assets/19153797/ccee93bf-b44e-4a6a-a830-70a719f852e7)

Alpha 2 with static NTK RoPE scaling can outperform drastically a base model above 2048 ctx, and a little above of compress defined by SuperHOT LoRA.

Now, when alpha is set to 4, you already have a penalty since the start on perplexity, and then, you can reach up to ~6000 context before perplex gets destroyed. With alpha 8, this is even worse.

Now, if you set a dynamic alpha based on the current length sequence, you get this.

![image](https://github.com/turboderp/exllama/assets/19153797/eb310601-ff14-4498-954d-f12e2292a145)

Where a dynamic NTK implementation with alpha 2, outperforms a static NTK implementation with alpha 4.

The formula of static NTK is:

Being `α` the alpha factor,

`rotary_embedding_base = rotary_embedding_base * α ^ (head_dim / (head_dim-2))`

While, for dynamic NTK:

Being `α` the alpha factor,

`α = (α * current sequence length / original model context length) - (α - 1)`

With a way to getting the current sequence length, this would be a way to try to implement this. It is not trivial, since alpha is changing with context, and such, it should be applied to every generation and not just when the model is getting loaded.

**Comment by Panchovix** [comment]
I've tried to do this this way at the moment.

I created def apply_formula, inside ExLlamaGenerator. Hard coded to alpha being 2 for now, until I find a way to add a parameter from model_init.py into generator.py.

```
    def apply_formula(self, sequence_actual_len: int):
        din_alpha = 2
        din_alpha = (din_alpha * sequence_actual_len / 2048) - (din_alpha - 1)
        return din_alpha 
```

Then, inside of `def beam_search(self):`

Below

```
# Insert in sequence

        self.sequence[0, c_seq_len] = best_token
        self.sequence_actual = torch.cat((self.sequence_actual, best_token.unsqueeze(0)), dim = 1)
```

I've added

```
        # Calculate current sequence length
        sequence_actual_len = self.sequence_actual.shape[-1]
        print (sequence_actual_len)
        # Apply NTK Dyanmic formula
        din_alpha = self.apply_formula(sequence_actual_len)
        # Update the alpha_value in the model
        self.model.config.alpha_value = din_alpha 
        # Update the rotary_embedding_base in the model
        self.model.config.calculate_rotary_embedding_base()
```

But it outputs just nonsense/gibberish, so probably I'm completely correct that I can change the alpha_value and the rotary_embedding_base on demand while generating.

**Comment by laoda513** [comment]
why not try a bit lora?

**Comment by turboderp** [comment]
What's your reason for assuming you can use the cached keys/values computed with a different setting for alpha? It doesn't seem to me that there's any way this could work without clearing the cache and starting inference from token 0 every time the positional embeddings are changed.

**Comment by Panchovix** [comment]
Thanks, @turboderp. Closing the issue as not possible.

**Comment by aikitoria** [comment]
@Panchovix I'm curious why this was closed as not possible. Is having to clear the cache on changing the size a problem? From my understanding the cache has to be reset often anyway once a conversation reaches the context limit and the UIs start truncating the start, so having it start scaling up the context instead would still be a major usability improvement. What am I missing?

**Comment by Panchovix** [comment]
> @Panchovix I'm curious why this was closed as not possible. Is having to clear the cache on changing the size a problem? From my understanding the cache has to be reset often anyway once a conversation reaches the context limit and the UIs start truncating the start, so having it start scaling up the context instead would still be a major usability improvement. What am I missing?

I haven't tried since, but it was because I didn't know how cache worked on exllamav1 and how to apply dynamic NTK besides normal conventions. (Since static NTK is just changing the rotary embeddings and apply it on load, while dynamic NTK has to be calculated for each time you do inference so cache has to be involved)
