### ISSUE TITLE
How to force an instance to stick to only a single GPU?

### ISSUE THREAD

**Issue by nikshepsvn** [turboderp/exllama#130]
``` def create_device_string(arr_size, ram, index):
        # Initialize array with zeros
        arr = [0] * arr_size

        # Replace the element at the specified index with 'ram'
        if index < arr_size:
            arr[index] = ram
        else:
            print("Index out of range")

        return ",".join(map(str, arr))

    num_devices = torch.cuda.device_count()
    devices = [torch.device(f"cuda:{i}") for i in range(num_devices)]
    processes = []
    mp.set_start_method("spawn", force=True)  # set the start method to 'spawn'

    for device in devices:
        new_config = copy.deepcopy(config)
        new_config.set_auto_map(create_device_string(num_devices, 20, device.index))
        p = mp.Process(
            target=ExLlamaWorker,
            args=(args.batch_size, new_config, args.tokenizer, device.index),
        )
        p.start()
        processes.append(p)
```
so im trying to run multiple exllama workers in parallel but for some reason my GPU usage increaes and then just dips to 0 again, I'm guessing something is happening due to CUDA context etc? Is there any way to isolate a GPU to a specific GPU and nothign else?

**Comment by nikshepsvn** [comment]
I've tried setting CUDA_VISIBLE_DEVICES as well but for some reason I can't get 4 instaces to run on 4 GPUs, with CUDA_VISIBLE_DEVICES set they just crash and using the set_auto_map causes them to run on the last two GPUs only (first one dies when third GPU starts and second one dies after forth GPU starts)

**Comment by nikshepsvn** [comment]
nvm, this is probably a limitation of python and I can get around it by starting the worker process from outside python rather than having python manage threads

**Comment by turboderp** [comment]
ExLlama currently doesn't support multiple instances. There will be an update soon that should allow this. But yes, in the meantime you'll need to launch separate processes.
