### ISSUE TITLE
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)

### ISSUE THREAD

**Issue by divrse** [turboderp/exllama#135]
I get this error with exllama running elinas alpaca 4bit safetensors 

Previously i never got this issue, not sure if its going to impact performence or cause random crashes

I tried a fresh python virtualenv reinstalling requirements and still get the error

what do you think the cause / implications of this is? @turboderp

I also tried using my conda environment + virtual env, and still get the issue

It happens on initialization, though i may have also seen it when working with larger context sizes
logs:

-- Tokenizer: /path/to/gen-models/elinas_alpaca-30b-lora-int4/tokenizer.model
 -- Model config: /path/to/gen-models/elinas_alpaca-30b-lora-int4/config.json
 -- Model: /path/to/gen-models/elinas_alpaca-30b-lora-int4/alpaca-30b-4bit-128g.safetensors
 -- Sequence length: 2048
 -- Tuning:
 -- --matmul_recons_thd: 8
 -- --fused_mlp_thd: 2
 -- --sdp_thd: 8
 -- Options: []
 -- Loading model...
 -- Loading tokenizer...
 -- Groupsize (inferred): 128
 -- Act-order (inferred): no
 -- Sessions stored in: /path/to/exllama_sessions/
Opening in existing browser session.
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)

**Comment by turboderp** [comment]
Do you get this with other models as well? It sounds like it's related to Chromium, AMD drivers and Wayland..?

**Comment by turboderp** [comment]
This seems to have gone stale.
