### ISSUE TITLE
Support non-Llama architectures

### ISSUE THREAD

**Issue by dred0n** [turboderp/exllama#136]
exLlama saved GPTQ, I've gone from 6 token/s to over 40, thank you!
Currently it's only supports Llama based models. 

Here's a few other promising architectures such as:
MPT
Falcon
SalesForce
StarCoder
ChatGLM

Are there plans to support these other architectures?

**Comment by EyeDeck** [comment]
Must admit I'm interested in Falcon 40B; a 4-bit quantized model is like 22.5GB, which might _just_ fit on a 24GB card using an exllama-style approach. Currently it requires considerably more, including Transformers overhead.
Notably, its use of multi-query attention, as opposed to multi-head attention like LLaMA, allegedly reduces the VRAM required for context by at least an order of magnitude, so (again, allegedly) 2048 context only requires about 240MB of VRAM.
Then again, working out a way to use multi-query attention with LLaMA might be possible too. At least, some of the Meta researchers [apparently think so](https://github.com/facebookresearch/llama/issues/187#issuecomment-1465894419).

**Comment by dred0n** [comment]
I hope Meta decides to release a version 2 but I'm not counting on it anytime soon. 
Do you think exllama-style inference would be possible with multi-query attention model like Falcon? 
If so, what would be involved in implementing the changes?

**Comment by turboderp** [comment]
I have no plans at the moment to support other architectures, other quantization methods, online APIs (ChatGPT?), or anything like that. I just don't have the time.

As for what would be involved in those changes, it would require studying the model and any existing implementations, writing a second code path for that model, testing it as much as possible, testing that it hasn't broken anything in the other code path, and then maintaining both going forward.
