### ISSUE TITLE
Long Net Dilated Attention (Drop in O(Nd) attention replacement?)

### ISSUE THREAD

**Issue by CoffeeVampir3** [turboderp/exllama#137]
<https://arxiv.org/pdf/2307.02486.pdf>

This paper makes some very bold claims: 
"...its dilated attention is a drop-in replacement for standard attention, which can be seamlessly
integrated with the existing Transformer-based optimization."

According to the paper, their attention mechanism is O(Nd) which if true is an absurd improvement to complexity.

![image](https://github.com/turboderp/exllama/assets/48565901/37a75f0e-d78a-42d7-a13e-35403dde5158)

I'm investigating this right now but I wanted to bring it to your attention as this could potentially be a breakthrough for context length.

**Comment by turboderp** [comment]
I've seen the paper, yes, and I'm not a fan of sensationalist titles like this. Why a billion tokens? Why not a trillion, or a quintillion? 

This means little for generation where attention is _already_ a linear operation. For training, sparse attention offers some benefits, and although their method looks a lot more like O(n log n) than O(n) from a quick glance, the difference there isn't huge and this might be the SOTA sparse-attention approach for all we know.

It doesn't really matter, though, until someone decides to invest the money and produces a large pretrained model using the method. If you want to see it in action on toy datasets, [Phil Wang](https://github.com/lucidrains?tab=repositories) will probably get to it soon enough, but there's not exactly a shortage of revolutionary new approaches to long-range attention for him to try out, so you may have to wait a little bit.
