### ISSUE TITLE
Fix for Pascal generation not working.

### ISSUE THREAD

**Issue by noblespade** [turboderp/exllama#139]
I had the issue mentioned here: https://github.com/oobabooga/text-generation-webui/issues/2949

Generation with exllama was extremely slow and the fix resolved my issue. After starting oobabooga again, it did not work anymore. The console is stuck on "INFO:Loading Manticore-13B-Chat-Pyg-Guanaco-SuperHOT-8K-GPTQ... WARNING:Exllama module failed to load. Will attempt to load from repositories."

But nothing happens at all.

I am sorry, i am very new to all this and can't understand why it worked one time and then exllama seemingly can't be loaded from repositories anymore. No changes, no error messages.

**Comment by turboderp** [comment]
You might have more luck raising this issue in the oobabooga repo. I have no idea what it would be attempting to load from repositories, and ooba uses a fork of ExLlama packaged as a library which may or may not have the fix applied.

**Comment by noblespade** [comment]
Thank you for your kind reply! I will try my luck there and close this issue.
