### ISSUE TITLE
How to use >2k context size?

### ISSUE THREAD

**Issue by vadi2** [turboderp/exllama#147]
From reading https://huggingface.co/TheBloke/wizard-vicuna-13B-SuperHOT-8K-GPTQ I get the sense that exllama supports context sizes greater than 2k - as part of oogabooga, anyhow.

When I load the model in the webui the sequence length shown is 2048, and trying a prompt larger than 2048 causes the python process to peg one cpu core indefinitely:

![image](https://github.com/turboderp/exllama/assets/110988/d3cde19c-1529-4b21-8926-acd6b4b19a89)

Is a greater context size supported in the exllama webui as well?

**Comment by EyeDeck** [comment]
For that model, you'd launch with `-cpe 4 -l 8192` (or `--compress_pos_emb 4 --length 8192`), possibly reducing length if you're VRAM limited and start OOMing once context has grown enough.
Some instructions that are going around say you can use e.g. `-cpe 2 -l 4096` (e.g. for 33B on 24GB VRAM, which OOMs around 3400-3600 tokens anyway), but you shouldn't do that, `cpe` should be set equal to whatever the finetune was done with or the model will act stupid, regardless of what `length` is limited to.

You can also try NTK scaling by setting `-a` (`--alpha`), for that you do _not_ want one of the older linear scaling finetunes, just use a regular 2k model. Without a finetune, `-a 2` will go up to ~3400 before exploding, `-a 4` will do ~5500, and `-a 8` will do ~9000.
Finetuning also helps with NTK scaling, but it's not strictly necessary like it is for linear scaling. At the time of writing, the only NTK finetunes I know of are a [SuperHOT 8k LoRA](https://huggingface.co/kaiokendev/test-superhot-13b-ntk-8) and [Airoboros 16k](https://huggingface.co/bhenrym14/airoboros-33b-gpt4-1.4.1-NTK-16384-GPTQ), but this tech has only been around for a few days, so expect more of those in the future.
Also, these "`-a` vs context" numbers will probably be outdated soon, as exllama still uses a version of NTK scaling as it was originally introduced, which has already been significantly improved upon [here](https://github.com/jquesnelle/scaled-rope/pull/1), and someone will probably port these changes here sooner or later.

**Comment by Ph0rk0z** [comment]
Another vote for NTK. No tuning and better perplexity. Covers basically the reasonable range for a 30b in 24gb, even at the lowest setting.

**Comment by vadi2** [comment]
Thanks! Lrger context size with -cpe -l worked.

What model would you recommend that I try with NTK? 

Will close the comment as we got the larger context size working.

**Comment by EyeDeck** [comment]
>What model would you recommend that I try with NTK?

I'm not particularly knowledgeable on this, but every model I've tried with NTK scaling isn't _that_ notably different from the same model without NTK scaling, except that scaled models are more prone to hallucination until you get a larger chunk of context going. Personally I kind of like stock LLaMA the most overall, but the same applies at regular 2k context.
