### ISSUE TITLE
Support for LLaMA-2-70B quants

### ISSUE THREAD

**Issue by Panchovix** [turboderp/exllama#165]
Hi there, thanks for all the hard work.

My system has 2x4090.

First, the FP16 model works if using bitsandbytes 4bit, with decent speeds.

`Output generated in 81.62 seconds (4.47 tokens/s, 365 tokens, context 3036, seed 640889223)`

I did a GPTQ from LLaMA-2-70B, without group size, act order true and true sequential. https://huggingface.co/Panchovix/LLaMA-2-70B-GPTQ-transformers4.32.0.dev0 and there's more quants here https://huggingface.co/TheBloke/Llama-2-70B-GPTQ

This model works in GPTQ-for-LLaMA, abeit *very slowly*.
`Output generated in 220.41 seconds (2.32 tokens/s, 511 tokens, context 2500, seed 725867733)`

Now, when trying to load the model on exllama, it works.

~~But then, when trying to do inference, I get (via ooba webui)~~
Exllama has been updated and now works with LLaMA-2-70B

**Comment by EyeDeck** [comment]
Yeah, ExLlama will need multi-query attention support before 70B or (not-yet-released) 34B will work with them. #163
The upside is that you'll probably be able to fit a lot more context, because despite the model being larger than 65B, with the MQA configuration Meta chose for 70B, it should reduce the memory requirement for context by a factor of 8.

LLaMA 2 13B already works on my machine (specifically [this](https://huggingface.co/TheBloke/Llama-2-13B-GPTQ/tree/gptq-4bit-128g-actorder_True) quant), I expect 7B would too, because those two still use MHA.

**Comment by llmlover** [comment]
@EyeDeck What do you suspect will the total memory consumption of the 70B model be after all implementations? Will it easily fit on two 4090s and will it roughly co sume as much as the 65B? (i tried cloud 2 4090s and it OOMd every time for thebloke 70b)

**Comment by EyeDeck** [comment]
Well, GQA makes the two models not directly comparable. This is assuming ExLlama receives the appropriate changes to support GQA models, considering ExLlama's significantly better memory efficiency than other current implementations:
>A 4-bit 128-groupsize quant of 65B is **34.7 GB**, while an equivalent quant of 70B is **36.7GB**. So to figure out how much context two 48GB cards should fit with the new model, a close approximation would be to find out how much you can currently fit using 65B with 2GB of VRAM free, then multiply whatever that number is by 8, and you should be pretty close.

So I'd _expect_ it to fit quite well, and you'd probably get a fair bit more context than current 65B.

**Comment by Panchovix** [comment]
> Well, GQA makes the two models not directly comparable. This is assuming ExLlama receives the appropriate changes to support GQA models, considering ExLlama's significantly better memory efficiency than other current implementations, and quoting my own napkin math from the discussions thread:
> 
> > A 4-bit 128-groupsize quant of 65B is **34.7 GB**, while an equivalent quant of 70B is **36.7GB**. So to figure out how much context two 48GB cards should fit with the new model, a close approximation would be to find out how much you can currently fit using 65B with 2GB of VRAM free, then multiply whatever that number is by 8, and you should be pretty close.
> 
> So I'd _expect_ it to fit quite well, and you'd probably get a fair bit more context than current 65B.

That's pretty impressive! I have tested more so far, and it seems that, on 2x4090,

* GPTQ for LLaMA: max context is about 2-2.5k, before it outputs at 0.05 tokens/s
* Transformers 4bit (bitsandbytes): max context is about 3-3.1k, then it gets OOM.

Those 2 methods use way more VRAM that exllama, or at least it did on llama v1.

**Comment by EyeDeck** [comment]
My guess is those aren't updated for GQA yet, and the new model just happens to work running MHA code anyway.

**Comment by Ph0rk0z** [comment]
Mine just d/l this morning. Haven't tried it yet. I have the bloke's 70b. I d/l the aligned chat on accident. Was expecting a slight context cut. I can usually do around 3400 on the 65b. My cards don't get used for display so they are fully empty. Guess it won't work yet.

**Comment by turboderp** [comment]
Should be up and running now.

```
python test_benchmark_inference.py -d /mnt/str/models/_test_models/Panchovix_LLaMA-2-70B-GPTQ-transformers4.32.0.dev0/ -gs 17,24 -p -ppl -v
 -- Perplexity:
 -- - Dataset: datasets/wikitext2_val_sample.jsonl
 -- - Chunks: 100
 -- - Chunk size: 2048 -> 2048
 -- - Chunk overlap: 0
 -- - Min. chunk size: 50
 -- - Key: text
 -- Tokenizer: /mnt/str/models/_test_models/Panchovix_LLaMA-2-70B-GPTQ-transformers4.32.0.dev0/tokenizer.model
 -- Model config: /mnt/str/models/_test_models/Panchovix_LLaMA-2-70B-GPTQ-transformers4.32.0.dev0/config.json
 -- Model: /mnt/str/models/_test_models/Panchovix_LLaMA-2-70B-GPTQ-transformers4.32.0.dev0/llama-2-70b-4bit.safetensors
 -- Sequence length: 2048
 -- Tuning:
 -- --matmul_recons_thd: 8
 -- --fused_mlp_thd: 2
 -- --sdp_thd: 8
 -- Options: ['gpu_split: 17,24', 'perf', 'validate', 'perplexity']
 ** Time, Load model: 14.82 seconds
 ** Time, Load tokenizer: 0.01 seconds
 -- Groupsize (inferred): None
 -- Act-order (inferred): no
 !! Model has empty group index (discarded)
 ** VRAM, Model: [cuda:0] 17,719.66 MB - [cuda:1] 16,574.28 MB
 ** VRAM, Cache: [cuda:0] 323.53 MB - [cuda:1] 304.00 MB
 -- Warmup pass 1...
 ** Time, Warmup: 2.34 seconds
 -- Warmup pass 2...
 ** Time, Warmup: 1.94 seconds
 -- Inference, first pass.
 ** Time, Inference: 1.95 seconds
 ** Speed: 986.77 tokens/second
 -- Generating 128 tokens, 1920 token prompt...
 ** Speed: 13.00 tokens/second
 -- Generating 128 tokens, 4 token prompt...
 ** Speed: 16.90 tokens/second
 ** VRAM, Inference: [cuda:0] 318.12 MB - [cuda:1] 317.29 MB
 ** VRAM, Total: [cuda:0] 18,361.31 MB - [cuda:1] 17,195.57 MB
 -- Loading dataset...
 -- Testing 100 chunks..........
 ** Perplexity: 4.2524
 -- Testing 8 chunks.
 ** Perplexity (reconstruct): 3.4033
 -- Testing 8 chunks.
 ** Perplexity (quant, token): 3.3822
 ** Generation: 'To be or not to be, that is the question.\nThe answer is yes, you should be using a VPN when torrenting.'
```

Also. Good advice there at the end. Don't copy that floppy. At least without a VPN.

It's not quite the completion I'd expect, but perplexity seems good overall, and the model seems very coherent, able to carry a conversation, build on a story or answer questions up to 4096 tokens before even getting to RoPE scaling.

As for that, with a 4096-token context it needs about 42.5 GB in total, thanks to GQA, which means there's a lot of headroom for longer contexts with scaling. Though I haven't really tested that yet.

**Comment by Panchovix** [comment]
@turboderp tested and working great! 41GB VRAM usage with no group size and act order true

`Output generated in 30.80 seconds (12.01 tokens/s, 370 tokens, context 3418, seed 228732740)`

**Comment by Panchovix** [comment]
To add even more, 12K and 16K works! This is magic!

`Output generated in 41.84 seconds (3.49 tokens/s, 146 tokens, context 12863, seed 1114540626)`

**Comment by Panchovix** [comment]
And with 16K,

`Output generated in 7.75 seconds (2.97 tokens/s, 23 tokens, context 15755, seed 1590590537)`

Still 47GB VRAM usage.

@Ph0rk0z 128 is the best middleground, since 32 has marginal better perplex but a lot more VRAM usage. These test were made with the non grouped version.

**Comment by SinanAkkoyun** [comment]
It truly amazes me how extremely fast you implemented GQA, just mindblowing

35960MiB / 49140MiB on a 2k context lenght with 9.14/11.65 tps, what a dream!

**Comment by turboderp** [comment]
Well I mean, it's a pretty small change. I had to read up on it to have some sense of what it was, but if you look at the commit it's only a couple of lines.

There's also a somewhat major optimization still to make because I've done it the quick-and-dirty way, same as what Meta did in the Transformers LlamaModel, by reshaping the entire (!) key/value cache during inference. It amounts to something on the order of 100 GB of extra VRAM access per forward pass, or 100 ms of extra time on a 4090. Depending on sequence length. It should be possible to do some type of broadcasting instead and make it go brr.

**Comment by SinanAkkoyun** [comment]
> make it go brr.

😍 Please! Am super excited

> or 100 ms of extra time on a 4090.

Isn't the whole inference per token taking 100ms at 10tps? Is this reshaping happening every single time for each token or how can I imagine that?

**Comment by TheBloke** [comment]
Great work!

Quick Q: does this require a recompile of the kernels? I'm wondering what to tell text-generation-webui users, like whether it will work for them automatically with the already provided wheel, or if they'll need to wait for text-generation-webui to update also.

**Comment by turboderp** [comment]
>Isn't the whole inference per token taking 100ms at 10tps?

This would be as the context grows very long. For me, the speed drops below 10 tokens/second at around 3500 tokens of context.

**Comment by Panchovix** [comment]
@TheBloke On ooba, they use wheels by default, which is using an older version. (https://github.com/jllllll/exllama)

They way to use it now on text-generation-webui, is by uninstalling the wheel directly, and then cloning exllama into `text-generation-webui\repositories`

**Comment by SinanAkkoyun** [comment]
> This would be as the context grows very long. For me, the speed drops below 10 tokens/second at around 3500 tokens of context.

I see, I was for some reason not referencing your 17tps figures. But still, do you actually mean taking away 100ms per token on your setup?

**Comment by turboderp** [comment]
@TheBloke Yes, it does require recompiling the kernel. So I guess the change has to propagate through a couple of different repos before it's all plug-and-play in text-generation-webui. And since it's so new, there could easily be bugs to sort out, and the fixes would be delayed as well.

It's kind of why I prefer the method I'm using for ExLlama which just compiles on the fly as necessary.

**Comment by Panchovix** [comment]
Closing, as now support is added, thanks to all!

**Comment by alain40** [comment]
Running Llama-2-70B-chat on 2x24GB with NVlink. 
No ctx scaling: native 4096 tokens.

- 4 bit, 64g, act-order
43.5 GB VRAM
6.5 t/s, mostly spent processing the prompt it seems (3900 tokens).

- 4 bit, 32g, act-order
46.4 GB VRAM
6 t/s

Thank you @turboderp, really great to be able to run such a powerful model locally.
