### ISSUE TITLE
Question: support for RAM allocation

### ISSUE THREAD

**Issue by saekiamae** [turboderp/exllama#177]
Exllama is amazing! Thank you for all the work!
My question is - would it be possible to add to gpu-split functionality ability to offload some part of the model to RAM? 
Speed of Exllama's generation is more than enough so I wouldn't mind sacrificing a bit of the speed for the additional VRAM 
(especially if without that additional 1GB let's say I won't be able to run my model at all :D)

Especially welcome would be some kind of dependency where there more I offload to RAM, the slower it gets 
so the user can tune it according to the needs whethere the speed or memory is more needed.

Thank you in advance for answer!! <3

**Comment by EyeDeck** [comment]
#52

If you can't fit the whole model on relatively recent Nvidia GPUs (Volta/Turing or newer, so 16, 20, 30, 40 series + workstation and data center equivalents), [llama.cpp](https://github.com/ggerganov/llama.cpp) is a better option. It'll run on basically anything.

**Comment by turboderp** [comment]
ExLlama doesn't have any code for CPU inference, so this wouldn't work. You're far better off with llama.cpp which is already really well optimized for CPU inference.

**Comment by saekiamae** [comment]
I did try it but if I run small model on llama cpp and offload all layers on GPU, it is still much slower than using Exlama - even though in both cases I offload everything on VRAM. So I guess merging Exlama optimisations for GPU inference with llamacpp optimizations for CPU inference we would have best from both worlds. But I understand that it may cost a lot of work. Thank you anyways <3
