### ISSUE TITLE
A potential rotation inconsistency of Dynamically Scaled RoPE

### ISSUE THREAD

**Issue by NormXU** [turboderp/exllama#178]
I notice there exists inconsistency with the rotation bases of the idea proposed by [Dynamically Scaled RoPE](https://www.reddit.com/user/kaiokendev).

You can check [this post](https://www.reddit.com/r/LocalLLaMA/comments/155bexn/a_potential_rotation_inconsistency_of_dynamically/) for more details.

While I haven't tested if a consistent rotation will benefit perplexity in any dataset or language model, I believe that, from a mathematical perspective, keeping consistency in the rotation base could potentially enhance the language model's ability to learn relative positions more effectively. My intuition suggests that this consistency might offer advantages in capturing relative position information. 

I will test it at my earliest convenience to validate this hypothesis.

**Comment by turboderp** [comment]
I'm not sure what I'm looking at here. I've specifically not implemented dynamic scaling because it doesn't make sense to perform attention across keys with position embeddings computed at different scales (or alpha values). Am I missing something?

**Comment by NormXU** [comment]
No, nothing is missing. I just drop a discussion here. Perhaps that post can be helpful to your implementation. 😃

**Comment by NormXU** [comment]
[Update] I have discussed with developers at huggingface and post a [blog ](https://normxu.github.io/A-Potential-Rotation-Inconsistency-of-Dynamic-Scaled-RoPE/)based on our [discussion](https://github.com/huggingface/transformers/issues/25104#issuecomment-1673576684). Hope this can be helpful to your implementation.
