### ISSUE TITLE
Change chatbort

### ISSUE THREAD

**Issue by SoftologyPro** [turboderp/exllama#181]
How do I change the defaults to not use chatbort?
I edited prompt_chatbort.txt to 
```
This is a conversation between a human and a highly intelligent AI. 
User: Hello
Bot: Hello
```
But when I start the webui/app I still get chatbort and the "OH MY GOD WHY DID YOU EVEN TALK TO ME I CAN'T BELIEVE IT" type replies.  I would like a more "normal" chatbot.  What am I missing?

**Comment by SoftologyPro** [comment]
Never mind, I found session.py and made the change there.

**Comment by turboderp** [comment]
You can change all those settings in the UI  ("fixed prompt" expands if you click it). But yes, if you want different defaults you'll have to change `session.py`.
