### ISSUE TITLE
Can I infer llama v2 70b on single gpu nvidia v100?

### ISSUE THREAD

**Issue by gabrielcustodio** [turboderp/exllama#186]
Gpu: Nvidia v100 16GB

**Comment by EyeDeck** [comment]
GPTQ 4-bit 70B with ExLlama is nearly 40GB of VRAM just to load; the minimum I would definitely expect to work is, like, 42GB. Using llama.cpp and 70B q3_K_S, it _just_ fits on two cards that add up to 34GB, with barely enough room for 1k context.
32GB of system RAM + 16GB of VRAM will work on llama.cpp, with like 1/3rd of the layers offloaded to GPU. Output speed won't be impressive, well under 1 t/s on a typical machine.

As for ExLlama, currently that card will fit 7B or 13B.
I know turboderp is looking into improved quantization methods for ExLLama v2, so if that pans out, and if LLaMA 2 34B is actually released, that might _just_ fit in 16GB, with limited context. Same with LLaMA 1 33B and _very_ limited context.
