### ISSUE TITLE
exwhisper

### ISSUE THREAD

**Issue by AmgadHasan** [turboderp/exllama#188]
Are there plans to add support for openai's whisper?

Thanks for this amazing project.

**Comment by BarfingLemurs** [comment]
@AmgadHasan looking for this? https://github.com/guillaumekln/faster-whisper

**Comment by AmgadHasan** [comment]
> @AmgadHasan looking for this? https://github.com/guillaumekln/faster-whisper
I've checked it out. It's based on CTranslate2. This is similar to llama's implementation in CTranslate.

However, I was wondering if there was a project to reimplement whisper to exwhispwer rather than using CTranslate2.

**Comment by turboderp** [comment]
I have no plans to look at Whisper for now. Focusing on the second iteration of ExLlama, and I can't branch out too far or nothing will actually ever get done.
