### ISSUE TITLE
Multi-line output is not displayed

### ISSUE THREAD

**Issue by temirov** [turboderp/exllama#198]
Jeff: Can you write a Haiku about being a chatbot?
Chatbort: Sure! Here's a haiku about being a chatbot:
Jeff: Can you write a Haiku about being a chatbot and format it so that all lines are concatenated and it's one sentence
Chatbort: Of course! Here's a Haiku about being a chatbot formatted in one sentence:
Jeff:

**Comment by turboderp** [comment]
Are you running the chat example with `--no_newline`?

**Comment by temirov** [comment]
`python example_chatbot.py -d ../models/llama-2-70b-Guanaco-QLoRA-GPTQ/ -un "Jeff" -p prompt_chatbort.txt -gs 17.2,24`

**Comment by temirov** [comment]
The `--no_newline` solved it! Thank you

Jeff: Hi, Chatbort!
Chatbort: Hello, Jeff.
Jeff: Can you write a Haiku about being a chatbot?
Chatbort: Sure, here it goes:
```
I am just a machine
With words to help you find
But I still have no feet
```
Jeff:
