### ISSUE TITLE
Kernel wouldn't compile in my conda env

### ISSUE THREAD

**Issue by Ph0rk0z** [turboderp/exllama#20]
Until I added a link from lib to lib64 it was unable to find the cuda libs. Compile would fail. Test kernel stuff is also out of date as the paths are wrong.

**Comment by turboderp** [comment]
Do you mean with the model or just the `compile.sh` script in cuda_test/? The cuda_test/ stuff is indeed out of date and I should probably just remove it until it's useful again. It isn't like a meaningful benchmark or anything.

But if you're having a problem running the model could you say some more about your setup? I'm using RunPod as a reference, and on their base config the C++ extension compiles and loads fine, as long as `ninja` is installed on top of at least PyTorch>=2.0

**Comment by Ph0rk0z** [comment]
When running the model it would fail compilation until I added a link from lib to lib64. I don't have a lib64 in conda even though it's a 64 bit system.

I have a conda environment with torch 2.0.1 and cuda extensions that works for transformers and a whole lot of other things. I was only using the 3090, also have a P40 but didn't try with that.

**Comment by turboderp** [comment]
It compiles the kernel for all available GPU architectures using `nvcc` and `gcc`, with the setup provided by your environment along with some flags automatically determined by Torch.

According to [the documentation](https://pytorch.org/docs/stable/cpp_extension.html#torch.utils.cpp_extension.load), Torch should pass the CUDA lib64 directory automatically, so maybe you have CUDA configured weirdly? You can enable the `verbose = True,` line at the top of cuda_ext.py to see the exact `nvcc` command line being used.

**Comment by Ph0rk0z** [comment]
I will try that next time.. I don't have a lib64 directory in the virtual environment. Other cuda things compile fine.

**Comment by MarcusLlewellyn** [comment]
Thanks to @mmealman for this tip! I only had to make sure the Nvidia CUDA toolkit was installed, and then it worked fine. Didn't need need to mess with any environment variables. This was on Windows 10 with WSL2 and Ununtu 20.04. Conda too, of course.

**Comment by turboderp** [comment]
I'll take it that this is resolved and I have too many open issues. Feel free to reopen or open another issue if necessary.
