### ISSUE TITLE
fixed seed doesn't work on ooba's webui

### ISSUE THREAD

**Issue by BadisG** [turboderp/exllama#201]
Hello,

I don't know if I should post this in there, but the fixed seed doesn't work on exllama or exllama_hf loader (it works fine on auto_gptq though). Is it a problem related to ooba's repo or yours? https://github.com/oobabooga/text-generation-webui/issues/3262

**Comment by turboderp** [comment]
ExLlama isn't completely deterministic because it relies on FP16 math with atomic addition rather than reduction.

**Comment by BadisG** [comment]
That's a shame, I don't know how can I see the effects of cfg if the outputs keeps changing for a fixed seed: https://github.com/oobabooga/text-generation-webui/pull/3325#issuecomment-1653487632

**Comment by turboderp** [comment]
Closing this here since determinism isn't in the cards at the moment. Perhaps somewhere down the line or in V2, but it's too large a rewrite and it's unclear what the benefits would be for the performance cost.
