### ISSUE TITLE
compile kernel

### ISSUE THREAD

**Issue by xiaoxiangshusheng** [turboderp/exllama#209]
If kernels have been modified, how to compile kernels?

**Comment by turboderp** [comment]
The kernels are compiled the first time `torch.utils.cpp_extension.load()` is called in `cuda_ext.py`. The result is cached in `~/.cache/torch_extensions`, and a rebuild is triggered whenever any of the files listed in `sources` has a new timestamp. Note that Torch uses ninja as a build system, and ninja only notices changes to the listed .cu and .cpp files. If you change a header file you have to also add some whitespace or something to any .cu or .cpp file that includes that header, or alternatively delete the cache in your home folder to force the rebuild.
