### ISSUE TITLE
How to change extend context with llama2? 

### ISSUE THREAD

**Issue by ShahZ181** [turboderp/exllama#215]

**Comment by ShahZ181** [comment]
How to change extend context with llama2? I tried changing alpha values and the compress_pos_emb but the mdeol seems to blurt nonsense after 4096 tokes? is there another way to do it becasue the same method works fo llama1 but not llama2?

**Comment by EyeDeck** [comment]
There's no significant difference between extended context techniques for LLaMA 1 and 2 except that LLaMA 1's native max length is 2048 and LLaMA 2 is 4096. If you want to double LLaMA 1 up to 4096, you need something like --alpha 2.4 or 2.6 (not sure the exact threshold but it's a little over 2), same with doubling LLaMA 2 to 8192.

If you want to use --compress_pos_emb, you need a model finetuned for it.
Here are some ExLlama-compatible LLaMA 2 quants that you can try:
[[LLongMA 2 7B](https://huggingface.co/TheBloke/LLongMA-2-7B-GPTQ)] `--compress_pos_emb 2` and length up to 8192
[[LLongMA 2 13B](https://huggingface.co/llama-anon/LLongMA-2-13b-GPTQ-4bit-32g)] `--compress_pos_emb 2` and length up to 8192
[[LLongMA 2 13B 16k](https://huggingface.co/EyeDeck/LLongMA-2-13b-16k-GPTQ-4bit-32g)]: `--compress_pos_emb 4` and length up to 16384

**Comment by turboderp** [comment]
Closing this. Feel free to reopen if necessary.
