### ISSUE TITLE
Multi-GPU

### ISSUE THREAD

**Issue by Fairfax-Mooresby** [turboderp/exllama#3]
I see from your own testing testing that you have multi-GPU working. 

Following the instructions and running test_benchmark_inference.py or test_chatbot.py they both worked on one of my RTX 3060's for a 13b model, and my other 2 3060's were detected (but not used)

Attempting to load a 33b llama model across all 3 cards I have led to cuda OOM error before the model loaded, as only a single card was used, with none of the other cards showing any VRAM usage. 

Any tricks to multi-card setups or parameters i should be passing?

**Comment by Fairfax-Mooresby** [comment]
...llygmalion-13b-4bit-128g.safetensors
 -- Sequence length: 2048
 -- Options: ['attention: pytorch_scaled_dp', 'matmul: switched', 'perf', 'ppl']
 ** Time, Load model: 6.85 seconds
 -- Groupsize (inferred): 128
 -- Act-order (inferred): no
 ** VRAM, Model: [cuda:0] 6,683.17 MB - [cuda:1] 0.00 MB - [cuda:2] 0.00 MB
 -- Inference, first pass.
 ** Time, Inference: 3.77 seconds
 ** Speed: 508.96 tokens/second
 -- Generating 128 tokens...
 ** Speed: 15.56 tokens/second
 ** VRAM, Inference: [cuda:0] 2,291.67 MB - [cuda:1] 0.00 MB - [cuda:2] 0.00 MB
 ** VRAM, Total: [cuda:0] 8,974.84 MB - [cuda:1] 0.00 MB - [cuda:2] 0.00 MB
 -- Loading dataset...
 -- Testing..........
 ** Perplexity: 5.9503
----------------------------------------------------------
...llama-30b-4bit-128g.safetensors
 -- Sequence length: 2048
 -- Options: ['attention: pytorch_scaled_dp', 'matmul: switched', 'perf', 'ppl']
Traceback (most recent call last):
  File "/home/user/Downloads/AI/exllama/test_benchmark_inference.py", line 132, in <module>
    wrapper = timer("Load model", lambda: ModelWrapper(args.tokenizer, args.config, args.model, args.attention, args.matmul, args.length, args.stream))
  File "/home/user/Downloads/AI/exllama/test_benchmark_inference.py", line 65, in timer
    ret = func()
  File "/home/user/Downloads/AI/exllama/test_benchmark_inference.py", line 132, in <lambda>
    wrapper = timer("Load model", lambda: ModelWrapper(args.tokenizer, args.config, args.model, args.attention, args.matmul, args.length, args.stream))
  File "/home/user/Downloads/AI/exllama/test_benchmark_inference.py", line 43, in __init__
    self.model = ExLlama(config)
  File "/home/user/Downloads/AI/exllama/model.py", line 767, in __init__
    tensor = tensor.to(device, non_blocking = True)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 58.00 MiB (GPU 0; 11.76 GiB total capacity; 9.70 GiB already allocated; 91.12 MiB free; 9.83 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by turboderp** [comment]
It doesn't automatically use multiple GPUs yet, but there is support for it. You just have to set the allocation manually.

For the benchmark and chatbot scripts, you can use the `-gs` or `--gpu_split` argument with a list of VRAM allocations per GPU. It will then load in layers up to the specified limit per device, though keep in mind this feature was added literally yesterday and this is all experimental still. Now, assuming 3060 is a 12GB card (right?) you could do something like this:

    python test_benchmark_inference.py -t <path_to_tokenizer.model> -c <path_to_config.json> \ 
      -m <path_to_model.safetensors> -p -ppl -gs 7.5,7.5,7.5

This would allocate 7.5 GB per GPU for model weights. In addition to the weights each GPU also needs to hold activations, part of the cache and whatever Torch needs for its internal buffers which is a little unpredictable. But if you run `nvidia-smi` while the benchmark is going you can get a fairly reliable estimate of how much memory is actually used on each device and then increase the allocation until you're close to the limit. If it fails with an OoM error like above, you have too much allocated on one GPU.

In theory you should only need two of your GPUs to run 30B, though.

**Comment by Fairfax-Mooresby** [comment]
Very cool, thank you. Working well. 

llama-30b-4bit-128g.safetensors
-- Sequence length: 2048
-- Options: ['attention: pytorch_scaled_dp', 'matmul: switched', 'perf', 'perplexity', 'gpu_split: 8.5,8.5']
** Time, Load model: 8.98 seconds
-- Groupsize (inferred): 128
-- Act-order (inferred): no
** VRAM, Model: [cuda:0] 8,331.70 MB - [cuda:1] 8,202.79 MB
-- Inference, first pass.
** Time, Inference: 8.22 seconds
** Speed: 233.56 tokens/second
-- Generating 128 tokens...
>** Speed: 10.14 tokens/second
** VRAM, Inference: [cuda:0] 2,052.51 MB - [cuda:1] 2,399.59 MB
** VRAM, Total: [cuda:0] 10,384.21 MB - [cuda:1] 10,602.37 MB
-- Loading dataset...
-- Testing..........
** Perplexity: 3342.9836

**Comment by turboderp** [comment]
Well, the perplexity score says it's not working very well. :) What model are you using, exactly? If you have a link to where you downloaded it I'd like to try it out to see what's wrong later tonight.
