### ISSUE TITLE
Can't compile on Windows

### ISSUE THREAD

**Issue by Panchvzluck** [turboderp/exllama#33]
Hi there, really amazing work that you're doing here.

I'm trying to run either the benchmark or the webui to test (I have 2x4090), but it seems it can't find the compiler or something similar?

The complete error is:

```
python .\webui\app.py
F:\ChatIAs\exllama\venv\lib\site-packages\torch\utils\cpp_extension.py:358: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
INFO: Could not find files for the given pattern(s)
Traceback (most recent call last):
  File "F:\ChatIAs\exllama\webui\app.py", line 9, in <module>
    import model_init
  File "F:\ChatIAs\exllama\model_init.py", line 1, in <module>
    from model import ExLlama, ExLlamaCache, ExLlamaConfig
  File "F:\ChatIAs\exllama\model.py", line 5, in <module>
    import cuda_ext
  File "F:\ChatIAs\exllama\cuda_ext.py", line 14, in <module>
    exllama_ext = load(
  File "F:\ChatIAs\exllama\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1283, in load
    return _jit_compile(
  File "F:\ChatIAs\exllama\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1508, in _jit_compile
    _write_ninja_file_and_build_library(
  File "F:\ChatIAs\exllama\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1610, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "F:\ChatIAs\exllama\venv\lib\site-packages\torch\utils\cpp_extension.py", line 2057, in _write_ninja_file_to_build_library
    _write_ninja_file(
  File "F:\ChatIAs\exllama\venv\lib\site-packages\torch\utils\cpp_extension.py", line 2200, in _write_ninja_file
    cl_paths = subprocess.check_output(['where',
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.
```

I have CUDA 11.8 and CUDA 12.1 on my system. I do specify when building for gtpq for example (with `$env:CUDA_PATH="CUDA_DIR"`, but here I'm not sure if it uses those or self built. Also, when specifying the CUDA version, it doesn't work either.

Maybe I'm missing something here?

Python 3.10.10
Windows 11 Pro
RTX 4090 x2
AMD Ryzen 7 7800X3D
VS2019

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community>nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:41:10_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
```

**Comment by turboderp** [comment]
I don't have a Windows PC to test on, so I'm not sure on the exact build steps. But it seems to be looking for `cl.exe` and not finding it. So it's not the CUDA stuff that's failing but plain C++. Since you have VS2019 installed, maybe it's just not in your path?

[Here's someone](https://github.com/turboderp/exllama/discussions/22) who got it running in WSL at least.

**Comment by Panchvzluck** [comment]
> I don't have a Windows PC to test on, so I'm not sure on the exact build steps. But it seems to be looking for `cl.exe` and not finding it. So it's not the CUDA stuff that's failing but plain C++. Since you have VS2019 installed, maybe it's just not in your path?
> 
> [Here's someone](https://github.com/turboderp/exllama/discussions/22) who got it running in WSL at least.

At least searching the file, it seems that cl.exe exist. Pretty weird it wouldn't be on the path.

I will try WSL and see how it goes, but also gonna keep trying on how to find a fix for pure Windows.

**Comment by allenbenz** [comment]
I've gotten to build on windows 10 without WSL.

If you're not seeing cl.exe on the path you probably need to run the developer console shell script to set the environment.
Something like `%comspec% /k "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"`

I also needed to add `extra_ldflags=['cublas.lib'],` to the `exllama_ext = load(` block in `cuda_ext.py`. You can also add `verbose=True` to that block to help diagnose issues.

If the cpp extension compilation gets into a bad place and you need to clean it, it gets stored somewhere under `%LOCALAPPDATA%\torch_extensions\torch_extensions\Cache`

**Comment by Panchvzluck** [comment]
> I've gotten to build on windows 10 without WSL.
> 
> If you're not seeing cl.exe on the path you probably need to run the developer console shell script to set the environment. Something like `%comspec% /k "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"`
> 
> I also needed to add `extra_ldflags=['cublas.lib'],` to the `exllama_ext = load(` block in `cuda_ext.py`. You can also add `verbose=True` to that block to help diagnose issues.
> 
> If the cpp extension compilation gets into a bad place and you need to clean it, it gets stored somewhere under `%LOCALAPPDATA%\torch_extensions\torch_extensions\Cache`

Just tried with your suggestions and got

```
[11/11] "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64/link.exe" exllama_ext.o cuda_buffers.cuda.o q4_matrix.cuda.o q4_matmul.cuda.o column_remap.cuda.o rms_norm.cuda.o rope.cuda.o half_matmul.cuda.o q4_mlp.cuda.o rep_penalty.o /nologo /DLL cublas.lib c10.lib c10_cuda.lib torch_cpu.lib torch_cuda.lib -INCLUDE:?warp_size@cuda@at@@YAHXZ torch.lib /LIBPATH:F:\ChatIAs\exllama\venv\lib\site-packages\torch\lib torch_python.lib /LIBPATH:F:\ChatIAs\exllama\venv\Scripts\libs "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\lib\x64" cudart.lib /out:exllama_ext.pyd
FAILED: exllama_ext.pyd
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64/link.exe" exllama_ext.o cuda_buffers.cuda.o q4_matrix.cuda.o q4_matmul.cuda.o column_remap.cuda.o rms_norm.cuda.o rope.cuda.o half_matmul.cuda.o q4_mlp.cuda.o rep_penalty.o /nologo /DLL cublas.lib c10.lib c10_cuda.lib torch_cpu.lib torch_cuda.lib -INCLUDE:?warp_size@cuda@at@@YAHXZ torch.lib /LIBPATH:F:\ChatIAs\exllama\venv\lib\site-packages\torch\lib torch_python.lib /LIBPATH:F:\ChatIAs\exllama\venv\Scripts\libs "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\lib\x64" cudart.lib /out:exllama_ext.pyd
LINK : fatal error LNK1104: cannot open file 'python310.lib''
ninja: build stopped: subcommand failed.
```

**Comment by Panchvzluck** [comment]
Okay, managed to build the kernel with @allenbenz suggestions and Visual Studio Code 2022. Vistual Studio Code 2019 just refused to work.

So, on Windows and exllama:

30B on a single 4090 does 30-35 tokens/s

65B on multigpu (2x4090) does 13-15 tokens/s

For comparison

30B on a single 4090 does 5-7 tokens/s with GPTQ on Windows

65B on multigpu (2x4090) does 2 tokens/s with GPTQ on Windows

A HUGE improvement

**Comment by Panchvzluck** [comment]
Okay, and as promised, after enabling Hardware Accelerated GPU Scheduling on Windows

65B on multigpu (2x4090) does **22+ tokens/s**

Unreal

```
Response generated in 2.7 seconds, 59 tokens, 22.15 tokens/second

Response generated in 3.5 seconds, 86 tokens, 24.62 tokens/second

Response generated in 2.6 seconds, 64 tokens, 24.19 tokens/second
```

Model used is Aeala_VicUnlocked-alpaca-65b-4bit_128g.

**Comment by turboderp** [comment]
What CPU are you using?

**Comment by turboderp** [comment]
So about as fast as mine (12900K) single threaded, bit slower but with somewhat faster RAM, and you're getting about the same speeds. More evidence of that damn CPU bottleneck. But I'm glad it's working so well.

I think I need to look into Hardware Accelerated GPU Scheduling, to see if Linux already does something equivalent by default, because that's a _big_ difference just from the scheduler.

**Comment by Panchvzluck** [comment]
@EyeDeck thanks for this, adding

`C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\<some-version-number>\bin\Hostx64\x64`

Is a must, else you would have to open exllama always from the developer console of VS2022.

**Comment by turboderp** [comment]
Checking for `os.name == "nt"` makes sense, yes.

I could also make it check if cl.exe is in the path, otherwise look for cl.exe in at least `C:\Program Files\Microsoft Visual Studio\2022\` and `C:\Program Files (x86)\Microsoft Visual Studio\2022\` and append the path accordingly.

Although, I would much prefer a pull request from someone who could write this up and actually test it.

**Comment by EyeDeck** [comment]
Hopefully #36 should do the trick.

**Comment by Panchvzluck** [comment]
Closing as PR https://github.com/turboderp/exllama/pull/36 fixes the compilation issues.
