### ISSUE TITLE
Pure C++ core instead of Python

### ISSUE THREAD

**Issue by gotzmann** [turboderp/exllama#35]
I'm curious, is it possible to extract just C++ / CUDA core from the project to integrate into external systems? Basically to have something like llama.cpp without Python at all, or just the initial step for compiling / building exllama.

**Comment by turboderp** [comment]
Well, the project is slowly becoming that, it seems. And there honestly isn't much left for it to do besides wasting some VRAM and adding a bit of overhead. Deriving layers from nn.Module is already redundant. So yeah, I think eventually I'll be able to remove it, or at least run it with no visible CUDA devices, just as a wrapper so I can still export PyTorch (CPU) tensors to the generator.
