### ISSUE TITLE
Feature Request: length_penalty support

### ISSUE THREAD

**Issue by Qubitium** [turboderp/exllama#48]
We are trying to port the transformer based gen code to exllama but did not find a configurable `length_penalty` control. Will this be on the road map? Thanks.

**Comment by turboderp** [comment]
Could you elaborate? There are various more-or-less hacky ways to force shorter or longer replies from a language model, but no standard way of doing it. Is there a particular front-end or UI you're referring to?

**Comment by Qubitium** [comment]
After looking at the transformer length_penalty doc it is actually beam_alpha. So, it is only applicable to multiple beams.

https://github.com/huggingface/transformers/issues/16930

**Comment by vpassanisi** [comment]
being able to bias towards shorter or longer responses would be a great addition

**Comment by hmellor** [comment]
Length penalty is now supported as you can see from https://github.com/vllm-project/vllm/blob/main/vllm/sampling_params.py#L105.

This issue can be closed.
