### ISSUE TITLE
ExLlamaDeviceMap's layers offload to CPU?

### ISSUE THREAD

**Issue by tiendung** [turboderp/exllama#52]
I would like to test run 7b model on my 4g vram 3050, look like exllama does not support offload model to CPU yet?

**Comment by turboderp** [comment]
It doesn't, no. I would require a whole separate implementation of the model to process CPU layers and I wouldn't expect that to come anytime soon. When it does, it probably won't be better than Llama.cpp anyway, but either way that's your best bet for running a 7B model on a 4 GB GPU right now.
