### ISSUE TITLE
Docker and ownership permissions

### ISSUE THREAD

**Issue by chrisbward** [turboderp/exllama#57]
Hi, I store my models on a local NAS, synology - which does not allow me to change ownership permissions of the files.

I get the following error when starting up the docker container with docker compose;

```
 ⠿ Network exllama_default  Created                                                                                                                                                                0.0s 
 ⠿ Container exllama-web-1  Created                                                                                                                                                                0.1s
Attaching to exllama-web-1
exllama-web-1  | chown: changing ownership of '/app/model/minotaur-13b-GPTQ-4bit-128g.no-act.order.safetensors': Operation not permitted
exllama-web-1  | chown: changing ownership of '/app/model/tokenizer.model': Operation not permitted
exllama-web-1  | chown: changing ownership of '/app/model/tokenizer_config.json': Operation not permitted
exllama-web-1  | chown: changing ownership of '/app/model/tokenizer.json': Operation not permitted
exllama-web-1  | chown: changing ownership of '/app/model/special_tokens_map.json': Operation not permitted
exllama-web-1  | chown: changing ownership of '/app/model/quantize_config.json': Operation not permitted
exllama-web-1  | chown: changing ownership of '/app/model/generation_config.json': Operation not permitted
exllama-web-1  | chown: changing ownership of '/app/model/config.json': Operation not permitted
exllama-web-1  | chown: changing ownership of '/app/model/README.md': Operation not permitted
exllama-web-1  | chown: changing ownership of '/app/model': Operation not permitted
exllama-web-1 exited with code 1
```

Unsure how to proceed

**Comment by chrisbward** [comment]
I've decided to comment out the `chown` found in entrypoint.sh;

```
# Ensure that bind-mounted directories are owned by the user that runs the service
# chown -R $RUN_UID:$RUN_UID $CONTAINER_MODEL_PATH
```

This allows me to get past, but now I'm hit with another error;

```
Attaching to exllama-web-1
exllama-web-1  | /app/cuda_ext.py:79: UserWarning: Failed to initialize NumPy: numpy.core.multiarray failed to import (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
exllama-web-1  |   none_tensor = torch.empty((1, 1), device = "meta")
exllama-web-1  | Traceback (most recent call last):
exllama-web-1  |   File "/app/webui/app.py", line 10, in <module>
exllama-web-1  |     from session import prepare_sessions, get_initial_session, Session, load_session, new_session
exllama-web-1  |   File "/app/webui/session.py", line 3, in <module>
exllama-web-1  |     from generator import ExLlamaGenerator
exllama-web-1  |   File "/app/generator.py", line 5, in <module>
exllama-web-1  |     class ExLlamaGenerator:
exllama-web-1  |   File "/app/generator.py", line 30, in ExLlamaGenerator
exllama-web-1  |     disallowed_tokens: list[int] or None
exllama-web-1  | TypeError: 'type' object is not subscriptable
exllama-web-1 exited with code 1

```

**Comment by turboderp** [comment]
Honestly I'm not very familiar with docker, but it does strike me as problematic for a container to change ownership of files in attached storage. @nikuya3 did the docker stuff. I wonder what they think?

I don't know what to make of that error message. Looks like it's failing when importing the Python module. And it's complaining about `numpy` even though that shouldn't be a requirement. Maybe it is, though?

**Comment by nikuya3** [comment]
For security reasons, exllama is run by a non-root user inside the container. However, because bind-mounted directories (`/app/model/` and ) are owned by `root` inside the container, the non-root user cannot access them. That's why the ownership has to be changed in `entrypoint.sh`, which unfortunately also changes the ownership at the host.

I think that's too opinionated, so I added a configuration option to disable this (#58). If you set `RUN_UID=0` in the `.env` file (or `--build-arg RUN_UID=0` if you use `docker build` directly), the command will be run as root inside the container and `chown` is not used. Note: this is not compatible with the existing image and you will have to build it again (`docker compose build` or `docker build`).

**Comment by nikuya3** [comment]
The second issue comes from the fact that the code uses type annotations that were introduced only in python 3.9 (https://docs.python.org/3/whatsnew/3.9.html#type-hinting-generics-in-standard-collections). It seems that the python version in your container is < 3.9, but it should be >=3.10. @chrisbward could you run `docker run --rm --entrypoint python3 exllama-web --version` and send me the output?

**Comment by turboderp** [comment]
This should be resolved now, I think.
