### ISSUE TITLE
Batch generation support

### ISSUE THREAD

**Issue by ri938** [turboderp/exllama#59]
Great repo.

Is there any plans to add support for batched generation? 

Any idea how much work this might be to achieve? I can potentially work on this if you can point me in the right direction.

**Comment by turboderp** [comment]
It's planned, yes. In fact the model already supports it (in theory, still need to test it thoroughly), it's just the generator that doesn't at the moment.

**Comment by turboderp** [comment]
Also there's already an issue for this (#50).
