### ISSUE TITLE
KeyError when loading GPTQ Model

### ISSUE THREAD

**Issue by mambug** [turboderp/exllama#62]
When trying to run the GPTQ Model (https://huggingface.co/TheBloke/starchat-beta-GPTQ) which works fine with other GPTQ loaders, I get the following using ExLlama via oobabooga webui:

```
line 40, in __init__
self.pad_token_id = read_config["pad_token_id"]
KeyError: 'pad_token_id'   
```

https://github.com/turboderp/exllama/blob/dd63e0734b7df5fcbd86d30ad82a582da25a3a73/model.py#L40

**Comment by turboderp** [comment]
StarChat isn't a Llama model, unfortunately. And ExLlama only supports Llama models. For now. See issue #14.

**Comment by mambug** [comment]
Oof - thanks! I missed that!
