### ISSUE TITLE
Possible to add a pip package?

### ISSUE THREAD

**Issue by CoffeeVampir3** [turboderp/exllama#63]
Heya, I'm writing a langchain binding for exllama, I'd love to be able to `pip install exllama` and be able to access the libraries in python natively, right now I'm not really sure how I'd ship the langchain module without creating my own binding library in pip, which seems very awkward.

**Comment by turboderp** [comment]
I'd love to package it up at some point, but a lot of it is still changing too much. The interface is mutating every other day, I'm adding in features, removing features, turning stateful stuff stateless and vice versa... I just don't think it's quite ready for a version number just yet.

**Comment by CoffeeVampir3** [comment]
Makes perfect sense, in the meantime I'll leave this example PR for people who wish to use exllama and langchain right now https://github.com/turboderp/exllama/pull/68#issue-1762326948

This seems like a good compromise for the time being I think.
