### ISSUE TITLE
Using QLoRA?

### ISSUE THREAD

**Issue by gameveloster** [turboderp/exllama#69]
I have been using QLoRA to finetune my model on my 3090, which previously could only perform inferences and not finetuning.

With the incredible improvements achieved with exllama, is it possible to combine both QLoRa and exllama so that the finetuning requirements are similar to the requirements for inferences?

**Comment by turboderp** [comment]
Possible, yes. Feasible? Idk. I've only just added regular LoRA support and it still needs to be tested. Then I can start looking at QLoRA, but I'm not sure how well it will mix with GPTQ. I definitely don't want to add `bitsandbytes` as a dependency, because that's, well, a mouthful.
