### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by KPTK** [turboderp/exllama#79]
Attempting to run python3 test_benchmark_inference.py -d /home/morpheus/Downloads/WizardLM-7B-uncensored-GPTQ -p -ppl or the example_basic.py returns an error.
Using: model_directory =  "/home/morpheus/Downloads/WizardLM-7B-uncensored-GPTQ"
Originally got this error: 

/home/morpheus/exwiz/exllama/cuda_ext.py:80: UserWarning: Failed to initialize NumPy: numpy.core.multiarray failed to import (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
  none_tensor = torch.empty((1, 1), device = "meta")
Traceback (most recent call last):
  File "test_benchmark_inference.py", line 3, in <module>
    from generator import ExLlamaGenerator
  File "/home/morpheus/exwiz/exllama/generator.py", line 3, in <module>
    from lora import ExLlamaLora
  File "/home/morpheus/exwiz/exllama/lora.py", line 7, in <module>
    class ExLlamaLora:
  File "/home/morpheus/exwiz/exllama/lora.py", line 15, in ExLlamaLora
    tensors: dict[torch.tensor]
TypeError: 'type' object is not subscriptable

Pip installed numpy and then go the same error but slightly different:

python3 test_benchmark_inference.py -d /home/morpheus/Downloads/WizardLM-7B-uncensored-GPTQ -p -ppl
Traceback (most recent call last):
  File "test_benchmark_inference.py", line 3, in <module>
    from generator import ExLlamaGenerator
  File "/home/morpheus/exwiz/exllama/generator.py", line 3, in <module>
    from lora import ExLlamaLora
  File "/home/morpheus/exwiz/exllama/lora.py", line 7, in <module>
    class ExLlamaLora:
  File "/home/morpheus/exwiz/exllama/lora.py", line 15, in ExLlamaLora
    tensors: dict[torch.tensor]
TypeError: 'type' object is not subscriptable

I can run auto gptq without issue but after two full days of trying to get this script to run (no web ui, just plain python interpretor) I have about given up. Anyone else running this on ubuntu? Im on 20.04(I dont think this is a distro issue). Dependencies all check out. Anyone successfully running this want to explain their setup or help with this error so I can get this up and running? Is there a different example script I should be running?

**Comment by turboderp** [comment]
The first thing that springs to mind is that maybe you're on an old Python version. Could you try upgrading to 3.10?

**Comment by TNT3530** [comment]
I was able to fix this issue in my rig by replacing the list declarations with brackets [ ] in both Lora.py and Generator.py
Works fine after for benchmarking and regular inference, though its probably not the best solution

**Comment by turboderp** [comment]
Yeah, typed list and dict declarations seem to be a new feature in Python 3.10. Or maybe 3.9. I could remove them, I suppose, but I think I'll just add Python 3.10 to the dependencies. I can't validate the rest of the code on older versions of Python, anyway.

**Comment by KPTK** [comment]
Fixx for me was to install appropriate python3-dev in the environment:  sudo apt-get install python3.10-dev
Please list this a dependency. Thanks for your hard work Turboderp. To infinity and beyond!

**Comment by turboderp** [comment]
I've had some long talks with GPT-4 about ways to include a Python version as a dependency, but it doesn't really seem to be possible. Best I could do would be check the version at runtime and at least output a warning. I think I'll do that.
