### ISSUE TITLE
Custom this repo for another architecture like BLOOM, MPT, Falcon

### ISSUE THREAD

**Issue by Iambestfeed** [turboderp/exllama#93]
Yah, it seems a bit ambitious but can you give me a clear direction on what should I do and what steps should be taken to build a repo like this for BLOOM?
Right now I'm still quite confused and also don't know what I'm missing for BLOOM.

**Comment by turboderp** [comment]
I haven't looked into BLOOM, so I don't know what it would take, exactly. But it's a different architecture, so you'd want to map out where it differs from Llama and then, just, make the corresponding changes in the code. This isn't Transformers where you just need a few magic words to make `AutoModel.from_pretrained` recognize a whole new architecture. You'd need a good understanding of how both models work.
