### ISSUE TITLE
OOM even with multiple GPUs (4x 3090 @ 24GB)

### ISSUE THREAD

**Issue by nikshepsvn** [turboderp/exllama#98]
![image](https://github.com/turboderp/exllama/assets/23241247/edb762fd-38e4-4ecb-8a94-7a57dcccfc93)

Command:  python exllama/webui/app.py --host 0.0.0.0:5000 -d ./30B-Lazarus-gptq-4bit --gpu_split 23,23,23,23 --length 8192 -cpe 4

**Comment by nikshepsvn** [comment]
![image](https://github.com/turboderp/exllama/assets/23241247/fae9cb81-762e-4aba-afe0-2df0d259bbe0)

**Comment by nikshepsvn** [comment]
I think this probably has to do with the extended context length setting and that not translating into the GPU mem split logic

**Comment by turboderp** [comment]
The `--gpu_split` is bad. ExLlama only expects the split for the weights. You also need some space per device for activations, and sadly it can't work that part out on its own (yet). Try with `--gpu_split 16,16,16,16`, or even less. Then you can run `nvidia-smi` to see how much memory ends up being used, and adjust accordingly.

**Comment by nikshepsvn** [comment]
![image](https://github.com/turboderp/exllama/assets/23241247/1807703c-3433-45fb-bc69-fbce274183ca)
![image](https://github.com/turboderp/exllama/assets/23241247/381de52f-3f85-41f6-9f96-206bc9126633)
So 10,10,10,10 worked but the memory split across GPUs is interesting

**Comment by nikshepsvn** [comment]
![image](https://github.com/turboderp/exllama/assets/23241247/d6dbb980-2bd8-4dbf-889c-bba56bf0d2c1)
also kernel crash when I inputted around 6k tokens, I have context set to 8k

**Comment by Jeduh** [comment]
Try 3,10,10,10

**Comment by turboderp** [comment]
Well, it splits the weights along layer lines so in your case you get 10 GB of weights on cuda:0, and then "the rest" on cuda:1, whatever that amounts to. There's nothing to put on cuda:2 and cuda:3, so those devices aren't used at all.

One way around this at the moment is just to reduce the split some more. A 33B model is probably around 19 GB, so you could try a split of 5,5,5,5 to start with. That way each GPU can keep a portion of the cache, instead of putting most of it on the first GPU.

There's also a modification I need to make for it to work better with very long contexts. Currently it tries to process all 6k tokens of a 6k token prompt at once, and there's really no need for that.

**Comment by nikshepsvn** [comment]
> Try 3,9,9,9

![image](https://github.com/turboderp/exllama/assets/23241247/ce174288-e243-4689-b213-91717145efb8)

**Comment by nikshepsvn** [comment]
> One way around this at the moment is just to reduce the split some more. A 33B model is probably around 19 GB, so you could try a split of 5,5,5,5 to start with. That way each GPU can keep a portion of the cache, instead of putting most of it on the first GPU.


![image](https://github.com/turboderp/exllama/assets/23241247/0f67fcc9-9194-404a-a2b6-a50fc1b99795)

Still no go, the 13B with 8k context works fine on a single card tho, goes up to 21-22GB vRAM usage

**Comment by nikshepsvn** [comment]
To be more specific, the kernel crashes on a large prompt (think 5-6k tokens), it works fine if I message it as usual, so not an instant crash by any means

**Comment by Jeduh** [comment]
BTW nik, when it does work later, the GPU split trick imo is to move most of the load onto the, other than first, GPUs in a way so that they all get filled to their split number and the rest gets flowed back into the first gpu hence leaving it a little lighter like 3,9,9,9 and 15,24

**Comment by turboderp** [comment]
I've pushed a commit that should limit the size of the attention operation in very large contexts by processing in batches of 2048 tokens instead of everything in one go. The benchmark script already does this, but I hadn't gotten around to updating the generator yet.

**Comment by turboderp** [comment]
I can run Llama-33B 128g with `-gs 9,24 -l 8192` with 2x24GB GPUs now, at least. A little room to spare on the second GPU, too.

**Comment by turboderp** [comment]
Can't get any good output without a tuned model, of course.

**Comment by nikshepsvn** [comment]
![image](https://github.com/turboderp/exllama/assets/23241247/c6fdbcc9-78ea-4476-8452-501c5226a249)
This is with a 30B model with the following command `root@C.6443641:~$ python exllama/webui/app.py --host 0.0.0.0:5000 -d ./30B-Lazarus-gptq-4bit --gpu_split 5,5,5,5 --length 8192 -cpe 4` -- works now, but consumes a TON of memory, is this expected?

**Comment by nikshepsvn** [comment]
I just had to play around with a little and I'm able to get some better results, ` python exllama/webui/app.py --host 0.0.0.0:5000 -d ./30B-Lazarus-gptq-4bit --gpu_split 10,10,10,10 --length 8192 -cpe 4` only uses around 40gigs, is there any way to be smart about GPU memory allocation with multi-GPU setups?

![image](https://github.com/turboderp/exllama/assets/23241247/1104051b-85e7-4a41-bbbb-6816f722b757)

**Comment by turboderp** [comment]
I've considered ways to make it smarter, but it's not entirely trivial to predict at load time what other buffers need to be allocated for each device during inference. It depends on a lot of different variables, and whatever logic I come up with would need to be changed whenever I make changes to other parts of the project. So for now I think it's just something users will have to fiddle with a bit.

**Comment by nikshepsvn** [comment]
Fair enough, thanks for the quick fix -- appreciate the effort you put into this project

**Comment by nikshepsvn** [comment]
Unrelated, but do you have any recommendations on reading material to be able to understand the exllama / llama.cpp codebases? Going to start with the transformers paper but I feel like there is a large gap I need to cover beyond that too

**Comment by turboderp** [comment]
Transformers paper is quite informative. Andrej Karpathy has [an excellent series](https://www.youtube.com/watch?v=VMj-3S1tku0&list=PLAqhIrjkxbuWI23v9cThsA9GvCAUhRvKZ) of video lectures. You'd want to familiarize yourself with Python, C++ and CUDA, but I don't know of any definitive resource on those.

One thing you could definitely do is get comfortable asking GPT-4. It's really good at explaining things, and it rarely gets anything completely wrong nowadays. It's also infinitely patient.

**Comment by nikshepsvn** [comment]
https://huggingface.co/kaiokendev/superhot-13b-16k-no-rlhf-test/discussions/1#6495d7c35e85f2810600a040
I did some testing here with kaiokendev's 16k lora, looks like PPL is lower on the 16K model even at 2K context, and it does better at higher contexts (16K) too. We might find benefit in scaling this further

**Comment by nikshepsvn** [comment]
Awesome, thanks a bunch -- going to dive deeper later today
